# Test FastAPI endpoints

GET http://127.0.0.1:8001/health
Accept: application/json

###

GET http://127.0.0.1:8001/ready
Accept: application/json

###

GET http://127.0.0.1:8001/docs
Accept: text/html

###

